name: Publish Linux wheels (3.10–3.12) to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-manylinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ---- Python 3.10 ----
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install maturin (3.10)
        run: pip install maturin

      - name: Build wheel (3.10, manylinux 2_34)
        run: maturin build --release --manylinux 2_34 -i python

      # ---- Python 3.11 ----
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install maturin (3.11)
        run: pip install maturin

      - name: Build wheel (3.11, manylinux 2_34)
        run: maturin build --release --manylinux 2_34 -i python

      # ---- Python 3.12 ----
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install maturin (3.12)
        run: pip install maturin

      - name: Build wheel (3.12, manylinux 2_34)
        run: maturin build --release --manylinux 2_34 -i python

      # Upload all built wheels to PyPI
      - name: Upload wheels to PyPI
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: maturin upload target/wheels/* -u __token__ -p $MATURIN_PYPI_TOKEN
