name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Runs only when you push a version tag (e.g. v0.1.3)

jobs:
  build-and-publish:
    name: Build and publish ZZignal
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install maturin
      - name: Install maturin
        run: pip install maturin

      # Build wheels (manylinux compatible for Linux)
      - name: Build wheels
        run: maturin build --release --manylinux off

      # Upload wheels as artifacts (so we can collect from all OS builds)
      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          name: zzignal-wheels
          path: target/wheels/*

  upload-to-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
      # Download all wheel artifacts from previous job
      - name: Download built wheels
        uses: actions/download-artifact@v4
        with:
          name: zzignal-wheels
          path: dist/

      # Install maturin for upload
      - name: Install maturin
        run: pip install maturin

      # Publish to PyPI
      - name: Upload to PyPI
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: maturin upload dist/* -u __token__ -p $MATURIN_PYPI_TOKEN
