name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install maturin
        run: pip install maturin

      - name: Build wheels (manylinux for Linux)
        run: maturin build --release --manylinux off

      - name: Upload built wheels (per OS)
        uses: actions/upload-artifact@v4
        with:
          name: zzignal-wheels-${{ matrix.os }}
          path: target/wheels/*

  upload-to-pypi:
    name: Upload all wheels to PyPI
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
      - name: Download Linux wheels
        uses: actions/download-artifact@v4
        with:
          name: zzignal-wheels-ubuntu-latest
          path: dist/

      - name: Download macOS wheels
        uses: actions/download-artifact@v4
        with:
          name: zzignal-wheels-macos-latest
          path: dist/

      - name: Download Windows wheels
        uses: actions/download-artifact@v4
        with:
          name: zzignal-wheels-windows-latest
          path: dist/

      - name: Install maturin
        run: pip install maturin

      - name: Upload to PyPI
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: maturin upload dist/* -u __token__ -p $MATURIN_PYPI_TOKEN
